import "./globals.css";

import { Quicksand } from "next/font/google";

const QuicksandDataFont = Quicksand({
  weight: "200",
  weight: "300",
  weight: "400",
  weight: "500",
  weight: "600",
  weight: "600",
  variable: "Quicksand",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={QuicksandDataFont.className}>{children}</body>
    </html>
  );
}
