const endpoints = {
  ADMIN_LOGIN_API: "admin/login",
  ADMIN_SIGNUP_API: "admin/register",
  ADMIN_LOGOUT_API: "admin/logout",
  ADMIN_GET_ACCOUNT_ADMIN_INFO: "admin/get-admin-info",
  GET_ALL_STORYS: "storys/get-all-storys",
  GET_STORY_INFO: "storys/get-story-info",
  ADMIN_ADD_GENREUSER_UPDATE_BLOCK_STATUS: "admin/user-update-block-status",
  ADMIN_ADD_AUTHOR_UPDATE_BLOCK_STATUS: "admin/author-update-block-status",
  ADMIN_UPDATE_STORY_INFO: "storys/admin-story-info-update",
  ADMIN_GET_RERESHTOKEN: "admin/admin-get-refresh-token",
  ADMIN_GET_STATISTICS: "statistics/statistics-admin",
  ADMIN_GET_STATISTICS_AUTHOR: "statistics/statistics-author",
  ADMIN_GET_LIST_USER: "admin/get-list-users",
  ADMIN_GET_LIST_AUTHOR: "admin/get-list-authors",
  ADMIN_GET_ACCOUNT_ADMIN_INFO_BY_ID: "admin/get-admin-account-by-id",
  GET_ALL_GENRES: "storys/get-all-genres",
  ADMIN_ADD_GENRE: "admin/add-genre",
  ADMIN_DELETE_GENRE: "admin/delete-genre",
  GET_STORY_OF_AUTHOR: "storys/get-storys-of-author",
  GET_USER_INFO_ACCOUNT: "user/user-info-account",
};
export default endpoints;
